-- MySQL Script generated by MySQL Workbench
-- 20 تموز, 2016 EEST 07:31:38 م
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema robotics
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `robotics` ;

-- -----------------------------------------------------
-- Schema robotics
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `robotics` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `robotics` ;

-- -----------------------------------------------------
-- Table `robotics`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `robotics`.`orders` ;

CREATE TABLE IF NOT EXISTS `robotics`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `cement` VARCHAR(45) NULL COMMENT '',
  `iron` VARCHAR(45) NULL COMMENT '',
  `mg` VARCHAR(45) NULL COMMENT '',
  `c` VARCHAR(45) NULL COMMENT '',
  `s` VARCHAR(45) NULL COMMENT '',
  `si` VARCHAR(45) NULL COMMENT '',
  `p` VARCHAR(45) NULL COMMENT '',
  `al` VARCHAR(45) NULL COMMENT '',
  `phone_number` VARCHAR(45) NULL COMMENT '',
  `created_date` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `robotics`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `robotics`.`users` ;

CREATE TABLE IF NOT EXISTS `robotics`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(45) NULL COMMENT '',
  `password` VARCHAR(45) NULL COMMENT '',
  `credit_card` VARCHAR(255) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
